name: Rust Multi-Platform Build

on:
  push:
    branches: [ "main" ]
    #tags:
    #  - "v*"
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:

          # ========== Linux ==========
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use-cross: true

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            use-cross: true

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: false

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use-cross: true

          #- os: ubuntu-latest
          #  target: armv7-unknown-linux-gnueabihf
          #  use-cross: true

          #- os: ubuntu-latest
          #  target: riscv64gc-unknown-linux-gnu
          #  use-cross: true

          # ========== macOS ==========
          - os: macos-latest
            target: x86_64-apple-darwin
            use-cross: false

          - os: macos-latest
            target: aarch64-apple-darwin
            use-cross: false

          # ========== Windows ==========
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            use-cross: false

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        #with:
          # dtolnay/rust-toolchain@master 版本 支持单位： offset, which may be written in years, months, weeks, or days. 【stable minus 8 releases】
          #toolchain: stable 18 months ago

      #- run: cargo test --all-features

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cross (Linux only)
        if: matrix.use-cross == true
        run: |
          unset RUSTFLAGS
          unset CARGO_BUILD_TARGET
          cargo install cross

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      # zigbuild (gnu) ≠ 需要 crt-static
      - name: Set RUSTFLAGS (musl only, NOT zig)
        if: contains(matrix.target, 'musl')
        run: echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV

      # ========== Build ==========
      - name: Build (cross)
        if: matrix.use-cross == true
        run: cross build --release --target ${{ matrix.target }}

      - name: Build (native)
        if: matrix.use-cross == false
        run: cargo build --release --target ${{ matrix.target }}

      - name: Install tree (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y tree

      - name: Install tree (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install tree

      - name: Install tree (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install tree -y

      - name: Show target directory tree
        #if: runner.os == 'Linux'
        run: |
          #if [ "${{ runner.os }}" = "Linux" ]; then
          #  sudo apt-get update
          #  sudo apt-get install -y tree
          
          #elif [ "${{ runner.os }}" = "macOS" ]; then
          #  brew install tree
          
          #elif [ "${{ runner.os }}" = "Windows" ]; then
          #  choco install tree -y
          #fi
          # sudo apt update
          # sudo apt install -y tree
          tree -L 4 target || true

      # ========== Package ==========
      - name: Package
        shell: bash
        run: |
          mkdir -p dist
          NAME=your_app

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            BIN=target/${{ matrix.target }}/release/$NAME.exe
            ZIP=$NAME-${{ matrix.target }}.zip
            powershell Compress-Archive -Path $BIN -DestinationPath dist/$ZIP
          else
            BIN=target/${{ matrix.target }}/release/$NAME
            TAR=$NAME-${{ matrix.target }}.tar.gz
            tar -czvf dist/$TAR -C $(dirname $BIN) $(basename $BIN)
          fi

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.target }}
          path: dist/*